/**
 * @packageDocumentation
 * @module api.functional.chatting
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IChatting } from "../../structures/chatting/IChatting";

/**
 * @controller ChattingController.chat
 * @path POST /chatting
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function chat(
  connection: IConnection,
  input: IChatting.IChatInput,
): Promise<chat.Output> {
  return !!connection.simulate
    ? chat.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...chat.METADATA,
          template: chat.METADATA.path,
          path: chat.path(),
        },
        input,
      );
}
export namespace chat {
  export type Input = IChatting.IChatInput;
  export type Output = null | Array<IChatting.IResponse>;

  export const METADATA = {
    method: "POST",
    path: "/chatting",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/chatting";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): null | Array<IChatting.IResponse> =>
    typia.random<null | Array<IChatting.IResponse>>(g);
  export const simulate = (
    connection: IConnection,
    input: IChatting.IChatInput,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
